modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "batterystatusinfo"
version = "${file.jarVersion}"
displayName = "Battery Status Info"
logoFile = "icon.png"
credits = ""
authors = "Edgeburn Media, Sam Rolfes"
description = '''
Show in-game alerts about your battery status.
'''

[[dependencies.batterystatusinfo]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.batterystatusinfo]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "CLIENT"
